name=TMS9900
description=TMS9900 16-bit processor support for Ghidra. Implements complete disassembly and p-code semantics for the TI TMS9900 microprocessor.
author=cvpeck
createdOn=
version=@extversion@
